FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.version"="0.1.0"
LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IGFuZHJvaWQtYXBwLWFwYgpkZXNjcmlwdGlvbjogU2V0cyB1cCBh\
biBBbmRyb2lkIEFwcCByZXByZXNlbnRhdGlvbi4KYmluZGFibGU6IEZhbHNlCmFzeW5jOiBvcHRp\
b25hbAp0YWdzOiAKICAtIG1vYmlsZQptZXRhZGF0YToKICBkaXNwbGF5TmFtZTogQW5kcm9pZCBB\
cHAKICBjb25zb2xlLm9wZW5zaGlmdC5pby9pY29uQ2xhc3M6IGZhIGZhLWFuZHJvaWQKICBpbWFn\
ZVVybDogImltYWdlcy9sb2dvcy9hbmRyb2lkLnBuZyIKICBkb2N1bWVudGF0aW9uVXJsOiAiaHR0\
cDovL2RvY3MuYWVyb2dlYXIub3JnIgogIHNlcnZpY2VOYW1lOiBhbmRyb2lkLWFwcApwbGFuczoK\
ICAtIG5hbWU6IGRlZmF1bHQKICAgIGRlc2NyaXB0aW9uOiBTZXRzIHVwIGFuIEFuZHJvaWQgQXBw\
IHJlcHJlc2VudGF0aW9uLgogICAgZnJlZTogVHJ1ZQogICAgbWV0YWRhdGE6IHt9CiAgICBwYXJh\
bWV0ZXJzOiAKICAgIC0gbmFtZTogYXBwTmFtZQogICAgICByZXF1aXJlZDogVHJ1ZQogICAgICBk\
ZWZhdWx0OiBteWFwcAogICAgICB0eXBlOiBzdHJpbmcKICAgICAgdGl0bGU6IEFwcGxpY2F0aW9u\
IE5hbWUKICAgIC0gbmFtZTogYXBwSWRlbnRpZmllcgogICAgICByZXF1aXJlZDogVHJ1ZQogICAg\
ICB0eXBlOiBzdHJpbmcKICAgICAgdGl0bGU6IFBhY2thZ2UgTmFtZQ=="

COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
COPY mobile /usr/bin
RUN chmod -R g=u /opt/{ansible,apb}
USER apb
