- name: "Get the name of the service instance"
  shell: oc get serviceinstance --namespace={{ namespace }} -o jsonpath='{.items[?(@.spec.externalID=="{{ _apb_service_instance_id }}")].metadata.name}'
  when: _apb_service_instance_id is defined
  register: service_instance_name

- name: "Create android app representation yaml file"
  template:
    src: mobile-client.yml.j2
    dest: /tmp/mobile-client.yaml

- name: Create Android Mobile Client
  command: "oc create -f /tmp/mobile-client.yaml -n {{ namespace }}"
  changed_when: false